apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
        - name: mediawiki
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mariadb
            - name: DB_NAME
              value: wikidatabase
            - name: DB_USER
              value: wiki
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: db-password
          volumeMounts:
            - name: mediawiki-data
              mountPath: /var/www/html/images
      volumes:
        - name: mediawiki-data
          persistentVolumeClaim:
            claimName: mediawiki-pvc
