name: Deploy MediaWiki

on:
  push:
    branches:
      - Thoughtworks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push MediaWiki image
      run: |
        docker build -t <your_docker_repo>/mediawiki:latest .
        docker push <your_docker_repo>/mediawiki:latest

    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v1
      with:
        namespace: default
        manifests: |
          helm-charts/mariadb/templates/deployment.yaml
          helm-charts/mariadb/templates/service.yaml
          helm-charts/mediawiki/templates/deployment.yaml
          helm-charts/mediawiki/templates/service.yaml
        images: |
          <your_docker_repo>/mediawiki:latest
